version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changemeinprod!
      MYSQL_DATABASE: productDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: changemeinprod!
    ports:
      - "3306:3306"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8000:8080"
#volumes:
#  pgdata:
#    driver: local
